version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.simple
    container_name: vrijwonen-web
    ports:
      - "8080:80"
    volumes:
      - ./htdocs:/var/www/html
      - ./app:/var/www/html/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=vrijwonen
      - DB_USER=root
      - DB_PASS=password
    networks:
      - vrijwonen-network

  db:
    image: mariadb:10.9
    container_name: vrijwonen-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vrijwonen
      MYSQL_USER: vrijwonen
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./vrijwonen_public.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./mock_data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - vrijwonen-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vrijwonen-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - db
    networks:
      - vrijwonen-network

volumes:
  db_data:

networks:
  vrijwonen-network:
    driver: bridge
