-- Comprehensive Mock Data for Vrij Wonen
-- This file contains sample data for all tables

-- Clear existing data
DELETE FROM connectprop;
DELETE FROM inquiries;
DELETE FROM objects;
DELETE FROM staff;
DELETE FROM properties;
DELETE FROM cities;

-- Reset auto-increment
ALTER TABLE cities AUTO_INCREMENT = 1;
ALTER TABLE properties AUTO_INCREMENT = 1;
ALTER TABLE objects AUTO_INCREMENT = 1;
ALTER TABLE staff AUTO_INCREMENT = 1;
ALTER TABLE inquiries AUTO_INCREMENT = 1;

-- Insert Cities (Original Dutch cities list)
INSERT INTO cities (id, citiename) VALUES
(106, '\'s-Gravenhage'),
(131, '\'s-Hertogenbosch'),
(2, 'Aa en Hunze'),
(3, 'Aalsmeer'),
(4, 'Aalten'),
(5, 'Achtkarspelen'),
(6, 'Alblasserdam'),
(7, 'Albrandswaard'),
(8, 'Alkmaar'),
(9, 'Almelo'),
(10, 'Almere'),
(11, 'Alphen aan den Rijn'),
(12, 'Alphen-Chaam'),
(13, 'Altena'),
(14, 'Ameland'),
(15, 'Amersfoort'),
(16, 'Amstelveen'),
(17, 'Amsterdam'),
(18, 'Apeldoorn'),
(19, 'Arnhem'),
(20, 'Assen'),
(21, 'Asten'),
(22, 'Baarle-Nassau'),
(23, 'Baarn'),
(24, 'Barendrecht'),
(25, 'Barneveld'),
(26, 'Beek'),
(27, 'Beekdaelen'),
(28, 'Beesel'),
(29, 'Berg en Dal'),
(30, 'Bergeijk'),
(31, 'Bergen (L.)'),
(32, 'Bergen (NH.)'),
(33, 'Bergen op Zoom'),
(34, 'Berkelland'),
(35, 'Bernheze'),
(36, 'Best'),
(37, 'Beuningen'),
(38, 'Beverwijk'),
(39, 'De Bilt'),
(40, 'Bladel'),
(41, 'Blaricum'),
(42, 'Bloemendaal'),
(43, 'Bodegraven-Reeuwijk'),
(44, 'Boekel'),
(45, 'Borger-Odoorn'),
(46, 'Borne'),
(47, 'Borsele'),
(48, 'Boxtel'),
(49, 'Breda'),
(50, 'Brielle'),
(51, 'Bronckhorst'),
(52, 'Brummen'),
(53, 'Brunssum'),
(54, 'Bunnik'),
(55, 'Bunschoten'),
(56, 'Buren'),
(57, 'Capelle aan den IJssel'),
(58, 'Castricum'),
(59, 'Coevorden'),
(60, 'Cranendonck'),
(61, 'Culemborg'),
(62, 'Dalfsen'),
(63, 'Dantumadiel'),
(64, 'Delft'),
(65, 'Deurne'),
(66, 'Deventer'),
(67, 'Diemen'),
(68, 'Dijk en Waard'),
(69, 'Dinkelland'),
(70, 'Doesburg'),
(71, 'Doetinchem'),
(72, 'Dongen'),
(73, 'Dordrecht'),
(74, 'Drechterland'),
(75, 'Drimmelen'),
(76, 'Dronten'),
(77, 'Druten'),
(78, 'Duiven'),
(79, 'Echt-Susteren'),
(80, 'Edam-Volendam'),
(81, 'Ede'),
(82, 'Eemnes'),
(83, 'Eemsdelta'),
(84, 'Eersel'),
(85, 'Eijsden-Margraten'),
(86, 'Eindhoven'),
(87, 'Elburg'),
(88, 'Emmen'),
(89, 'Enkhuizen'),
(90, 'Enschede'),
(91, 'Epe'),
(92, 'Ermelo'),
(93, 'Etten-Leur'),
(94, 'De Fryske Marren'),
(95, 'Geertruidenberg'),
(96, 'Geldrop-Mierlo'),
(97, 'Gemert-Bakel'),
(98, 'Gennep'),
(99, 'Gilze en Rijen'),
(100, 'Goeree-Overflakkee'),
(101, 'Goes'),
(102, 'Goirle'),
(103, 'Gooise Meren'),
(104, 'Gorinchem'),
(105, 'Gouda'),
(107, 'Groningen'),
(108, 'Gulpen-Wittem'),
(109, 'Haaksbergen'),
(110, 'Haarlem'),
(111, 'Haarlemmermeer'),
(112, 'Halderberge'),
(113, 'Hardenberg'),
(114, 'Harderwijk'),
(115, 'Hardinxveld-Giessendam'),
(116, 'Harlingen'),
(117, 'Hattem'),
(118, 'Heemskerk'),
(119, 'Heemstede'),
(120, 'Heerde'),
(121, 'Heerenveen'),
(122, 'Heerlen'),
(123, 'Heeze-Leende'),
(124, 'Heiloo'),
(125, 'Den Helder'),
(126, 'Hellendoorn'),
(127, 'Hellevoetsluis'),
(128, 'Helmond'),
(129, 'Hendrik-Ido-Ambacht'),
(130, 'Hengelo'),
(132, 'Heumen'),
(133, 'Heusden'),
(134, 'Hillegom'),
(135, 'Hilvarenbeek'),
(136, 'Hilversum'),
(137, 'Hoeksche Waard'),
(138, 'Hof van Twente'),
(139, 'Het Hogeland'),
(140, 'Hollands Kroon'),
(141, 'Hoogeveen'),
(142, 'Hoorn'),
(143, 'Horst aan de Maas'),
(144, 'Houten'),
(145, 'Huizen'),
(146, 'Hulst'),
(147, 'IJsselstein'),
(148, 'Kaag en Braassem'),
(149, 'Kampen'),
(150, 'Kapelle'),
(151, 'Katwijk'),
(152, 'Kerkrade'),
(153, 'Koggenland'),
(154, 'Krimpen aan den IJssel'),
(155, 'Krimpenerwaard'),
(156, 'Laarbeek'),
(157, 'Land van Cuijk'),
(158, 'Landgraaf'),
(159, 'Landsmeer'),
(160, 'Lansingerland'),
(161, 'Laren'),
(162, 'Leeuwarden'),
(163, 'Leiden'),
(164, 'Leiderdorp'),
(165, 'Leidschendam-Voorburg'),
(166, 'Lelystad'),
(167, 'Leudal'),
(168, 'Leusden'),
(169, 'Lingewaard'),
(170, 'Lisse'),
(171, 'Lochem'),
(172, 'Loon op Zand'),
(173, 'Lopik'),
(174, 'Losser'),
(175, 'Maasdriel'),
(176, 'Maasgouw'),
(177, 'Maashorst'),
(178, 'Maassluis'),
(179, 'Maastricht'),
(180, 'Medemblik'),
(181, 'Meerssen'),
(182, 'Meierijstad'),
(183, 'Meppel'),
(184, 'Middelburg'),
(185, 'Midden-Delfland'),
(186, 'Midden-Drenthe'),
(187, 'Midden-Groningen'),
(188, 'Moerdijk'),
(189, 'Molenlanden'),
(190, 'Montferland'),
(191, 'Montfoort'),
(192, 'Mook en Middelaar'),
(193, 'Neder-Betuwe'),
(194, 'Nederweert'),
(195, 'Nieuwegein'),
(196, 'Nieuwkoop'),
(197, 'Nijkerk'),
(198, 'Nijmegen'),
(199, 'Nissewaard'),
(200, 'Noardeast-Fryslân'),
(201, 'Noord-Beveland'),
(202, 'Noordenveld'),
(203, 'Noordoostpolder'),
(204, 'Noordwijk'),
(205, 'Nuenen, Gerwen en Nederwetten'),
(206, 'Nunspeet'),
(207, 'Oegstgeest'),
(208, 'Oirschot'),
(209, 'Oisterwijk'),
(210, 'Oldambt'),
(211, 'Oldebroek'),
(212, 'Oldenzaal'),
(213, 'Olst-Wijhe'),
(214, 'Ommen'),
(215, 'Oost Gelre'),
(216, 'Oosterhout'),
(217, 'Ooststellingwerf'),
(218, 'Oostzaan'),
(219, 'Opmeer'),
(220, 'Opsterland'),
(221, 'Oss'),
(222, 'Oude IJsselstreek'),
(223, 'Ouder-Amstel'),
(224, 'Oudewater'),
(225, 'Overbetuwe'),
(226, 'Papendrecht'),
(227, 'Peel en Maas'),
(228, 'Pekela'),
(229, 'Pijnacker-Nootdorp'),
(230, 'Purmerend'),
(231, 'Putten'),
(232, 'Raalte'),
(233, 'Reimerswaal'),
(234, 'Renkum'),
(235, 'Renswoude'),
(236, 'Reusel-De Mierden'),
(237, 'Rheden'),
(238, 'Rhenen'),
(239, 'Ridderkerk'),
(240, 'Rijssen-Holten'),
(241, 'Rijswijk'),
(242, 'Roerdalen'),
(243, 'Roermond'),
(244, 'De Ronde Venen'),
(245, 'Roosendaal'),
(246, 'Rotterdam'),
(247, 'Rozendaal'),
(248, 'Rucphen'),
(249, 'Schagen'),
(250, 'Scherpenzeel'),
(251, 'Schiedam'),
(252, 'Schiermonnikoog'),
(253, 'Schouwen-Duiveland'),
(254, 'Simpelveld'),
(255, 'Sint-Michielsgestel'),
(256, 'Sittard-Geleen'),
(257, 'Sliedrecht'),
(258, 'Sluis'),
(259, 'Smallingerland'),
(260, 'Soest'),
(261, 'Someren'),
(262, 'Son en Breugel'),
(263, 'Stadskanaal'),
(264, 'Staphorst'),
(265, 'Stede Broec'),
(266, 'Steenbergen'),
(267, 'Steenwijkerland'),
(268, 'Stein'),
(269, 'Stichtse Vecht'),
(270, 'Súdwest-Fryslân'),
(271, 'Terneuzen'),
(272, 'Terschelling'),
(273, 'Texel'),
(274, 'Teylingen'),
(275, 'Tholen'),
(276, 'Tiel'),
(277, 'Tilburg'),
(278, 'Tubbergen'),
(279, 'Twenterand'),
(280, 'Tynaarlo'),
(281, 'Tytsjerksteradiel'),
(282, 'Uitgeest'),
(283, 'Uithoorn'),
(284, 'Urk'),
(285, 'Utrecht'),
(286, 'Utrechtse Heuvelrug'),
(287, 'Vaals'),
(288, 'Valkenburg aan de Geul'),
(289, 'Valkenswaard'),
(290, 'Veendam'),
(291, 'Veenendaal'),
(292, 'Veere'),
(293, 'Veldhoven'),
(294, 'Velsen'),
(295, 'Venlo'),
(296, 'Venray'),
(297, 'Vijfheerenlanden'),
(298, 'Vlaardingen'),
(299, 'Vlieland'),
(300, 'Vlissingen'),
(330, 'De Wolden');

-- Insert Properties
INSERT INTO properties (id, propertie) VALUES
(1, 'Dicht bij het bos'),
(2, 'Dicht bij de stad'),
(3, 'In het Heuvelland'),
(4, 'Aan het water'),
(5, 'Moderne keuken'),
(6, 'Grote tuin'),
(7, 'Parkeerplaats'),
(8, 'Balkon'),
(9, 'Garage'),
(10, 'Nieuwe badkamer'),
(11, 'Houtkachel'),
(12, 'Zonnepanelen'),
(13, 'Airconditioning'),
(14, 'Sauna'),
(15, 'Zwembad');

-- Insert Staff (with hashed passwords)
INSERT INTO staff (id, username, email, passwordhash, sessionkey, admin) VALUES
(1, 'admin', 'admin@vrijwonen.nl', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '', 1),
(2, 'jan', 'jan@vrijwonen.nl', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '', 0),
(3, 'marie', 'marie@vrijwonen.nl', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '', 0);

-- Insert Objects (Houses) with local images
INSERT INTO objects (id, title, price, adress, postcode, cityid, description, mainimage, image2, image3, image4, image5, sold) VALUES
(1, 'Moderne eengezinswoning', 425000, 'Hoofdstraat 123', '1012AB', 17, 'Prachtige moderne eengezinswoning in het hart van Amsterdam. Deze woning beschikt over 4 slaapkamers, een moderne keuken en een gezellige woonkamer met openslaande deuren naar de tuin.', 'house_default', 'house_default', 'house_default', 'house_default', 'house_default', 0),

(2, 'Luxe appartement met uitzicht', 375000, 'Nieuwstraat 45', '2511BC', 106, 'Stijlvol appartement in Den Haag met prachtig uitzicht over de stad. 3 slaapkamers, open keuken en groot balkon. Perfect gelegen nabij het centrum.', 'house_default', 'house_default', 'house_default', 'house_default', 'house_default', 0),

(3, 'Landelijke villa', 650000, 'Dorpsstraat 78', '1234CD', 15, 'Ruime landelijke villa met grote tuin en zwembad. 5 slaapkamers, 3 badkamers en een prachtige keuken. Ideaal voor gezinnen die van rust houden.', 'house_default', 'house_default', 'house_default', 'house_default', 'house_default', 0),

(4, 'Stadsappartement', 295000, 'Marktplein 12', '3512AB', 285, 'Modern appartement in het centrum van Utrecht. 2 slaapkamers, open keuken en balkon met uitzicht op de markt. Perfect voor starters.', 'house_default', 'house_default', 'house_default', 'house_default', 'house_default', 0),

(5, 'Waterside woning', 550000, 'Kade 56', '3011AD', 246, 'Unieke woning aan het water in Rotterdam. 4 slaapkamers, moderne keuken en groot terras aan het water. Met eigen aanlegsteiger.', 'house_default', 'house_default', 'house_default', 'house_default', 'house_default', 0),

(6, 'Gerenoveerde boerderij', 485000, 'Boerenweg 89', '5678EF', 107, 'Prachtig gerenoveerde boerderij in Groningen. 6 slaapkamers, grote keuken en woonkamer. Met grote schuur en weiland. Perfect voor grote gezinnen.', 'house_default', 'house_default', 'house_default', 'house_default', 'house_default', 0),

(7, 'Penthouse appartement', 750000, 'Torenstraat 1', '1011AB', 17, 'Luxe penthouse in Amsterdam met panoramisch uitzicht. 3 slaapkamers, moderne keuken en groot dakterras. Met eigen lift en conciërge.', 'house_default', 'house_default', 'house_default', 'house_default', 'house_default', 0),

(8, 'Starterwoning', 225000, 'Beginnerslaan 34', '1234GH', 10, 'Betaalbare starterwoning in Almere. 2 slaapkamers, compacte keuken en kleine tuin. Perfect voor jonge stellen.', 'house_default', 'house_default', 'house_default', 'house_default', 'house_default', 0);

-- Connect Properties to Objects
INSERT INTO connectprop (objectid, propertieid) VALUES
-- Object 1 (Moderne eengezinswoning)
(1, 2), (1, 5), (1, 6), (1, 7), (1, 8),
-- Object 2 (Luxe appartement)
(2, 2), (2, 5), (2, 8), (2, 10),
-- Object 3 (Landelijke villa)
(3, 1), (3, 3), (3, 6), (3, 7), (3, 9), (3, 15),
-- Object 4 (Stadsappartement)
(4, 2), (4, 5), (4, 8),
-- Object 5 (Waterside woning)
(5, 4), (5, 5), (5, 6), (5, 7), (5, 8),
-- Object 6 (Gerenoveerde boerderij)
(6, 1), (6, 6), (6, 7), (6, 9), (6, 11),
-- Object 7 (Penthouse)
(7, 2), (7, 5), (7, 8), (7, 10), (7, 13),
-- Object 8 (Starterwoning)
(8, 2), (8, 6);

-- Insert Sample Inquiries
INSERT INTO inquiries (id, objectid, fullname, replyemail, message, handled) VALUES
(1, 1, 'Jan de Vries', 'jan.devries@email.com', 'Hallo, ik ben geïnteresseerd in deze woning. Kunnen we een bezichtiging plannen?', 0),
(2, 2, 'Marie van der Berg', 'marie.vandenberg@email.com', 'Mooie woning! Wat zijn de maandlasten ongeveer?', 0),
(3, 3, 'Piet Jansen', 'piet.jansen@email.com', 'Is er een garage bij deze villa?', 1),
(4, 4, 'Lisa Bakker', 'lisa.bakker@email.com', 'Perfect voor ons! Wanneer kunnen we kijken?', 0),
(5, 5, 'Tom Mulder', 'tom.mulder@email.com', 'Hoe diep is het water bij de aanlegsteiger?', 0);
